# cloudwatch-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
  namespace: backup-cw
data:
  cwagentconfig.json: |
    {
      "agent": {
        "region": "ap-northeast-1",
        "metrics_collection_interval": 60,
        "logfile": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
      },
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/containers/*.log",
                "log_group_name": "backup-cwtest",
                "log_stream_name": "{instance_id}"
              }
            ]
          }
        }
      }
    }
