datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: CloudWatch
        type: cloudwatch
        jsonData:
          authType: keys
          defaultRegion: ap-northeast-1
          assumeRoleArn: arn:aws:iam::{Account ID}:role/EKS-CloudWatch-Role
        secureJsonData:z
          aws_access_key_id: your_access_key_id
          aws_secret_access_key: your_secret_access_key

grafana.ini:
  auth.anonymous:
    enabled: true

service:
  type: LoadBalancer

rbac:
  create: true

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 30
  periodSeconds: 10
  failureThreshold: 6